### ISSUE TITLE
Implicit declaration of function 'JreAnnotationEquals' is invalid in C99

### ISSUE THREAD

**Issue by lucienkerlWIT** [google/j2objc#973]
I updated from J2ObjC version 2.0.3 to 2.1.1. After generating my ObjC sources I'm getting errors like in the title in one class. The error occurs in the translated ObjC file from javax.annotation.Tainted.java (https://chromium.googlesource.com/external/jsr-305/+/4e1f9dc708a57e175e76833b0d1b27212b74d0c5/ri/src/main/java/javax/annotation/Tainted.java).

```
- (jboolean)isEqual:(id)obj {
  return JreAnnotationEquals(self, obj); // <-- error occurs here
}

- (NSUInteger)hash {
  return JreAnnotationHashCode(self); // <-- and here
}
```

I already tried activating ARC by passing the argument `--use-arc`. This did not work because of an error like 'NSString can not be converted to Int in ARC mode'.

**Comment by tomball** [comment]
It sounds like the include path still uses the old j2objc version, as the declarations for those functions are in [J2ObjC_common.h](https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_common.h#L93), which is indirectly included by every file j2objc generates.

I'm confident annotations such as javax.annotation.Tainted build in 2.1.1, since we include the [jsr305 project](https://github.com/google/j2objc/tree/master/jsr305) in all distribution bundles (you'll find Taint.h in j2objc-2.1.1/include/javax/annotation). So an easy fix would be to stop building those annotations separately, as the Chromium copies are identical ([jsr305](https://jcp.org/en/jsr/detail?id=305) hasn't change in over ten years). Not building jsr305 won't help other translating other annotations, however, but it will speed up your build a little.

Check your build log to see if there are any remaining references to version 2.0.3 and fix or remove them. Clang (the C compiler) supports multiple include and library paths, so if your build has paths for both 2.0.3 and 2.1.1, the first one that has the #included file "wins" and the other paths are ignored. That means that even if you added the 2.1.1 bundle as an include path, it won't take effect if the 2.0.3 flag precedes it in the compiler's command line. An easy way to find old path references is to delete all old j2objc distributions from your system and fix whatever that breaks. There's no reason to ever have multiple versions of j2objc on your system.

A good way to avoid this in the future is to define a build variable like J2OBJC_HOME, then use it as the root for include and library paths. That way, upgrades only require changing one variable. An Xcode example of this can be found in [examples/Hello/Hello.xcconfig](https://github.com/google/j2objc/blob/master/examples/Hello/Hello.xcconfig#L7).
