### ISSUE TITLE
Support Java 1.8 Type Annotations

### ISSUE THREAD

**Issue by KasparEtter** [google/j2objc#722]
The "-source 8" flag works great for lambda expressions and default methods. Many thanks!

Could you also support the [type annotations](https://blogs.oracle.com/java-platform-group/entry/java_8_s_new_type) of Java 8? For my case it's actually sufficient if [ElementType.TYPE_USE](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/ElementType.html#TYPE_USE) in the [Target](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Target.html) meta-annotation is not rejected by the compiler ("TYPE_USE cannot be resolved or is not a field") and all occurrences of type annotations (e.g. `List<@Nonnull String>`) are just ignored during cross-compilation. (Thanks to [Retrolambda](https://github.com/orfjackal/retrolambda), my Java 8 code with such type annotations runs on Android as generic parameters are dropped anyway during compilation.)

How complicated is it to solve my problem? As I have no understanding of the J2ObjC codebase, could you at least point me into the direction of the necessary changes if you cannot support type annotations for time or other reasons?

Keep up the great work, I appreciate it a lot!

**Comment by tomball** [comment]
Please attach an example annotation and a short test class. It sounds like you may have hit an Eclipse JDT problem (it's the translator's front-end), so we can verify whether it's been fixed in a future JDT version with your test, or file a bug with the JDT team and attach it. If the problem is already fixed in the JDT, we can upgrade to it quickly if none of our other tests break.

**Comment by KasparEtter** [comment]
The following code compiles with Java 1.8 but results in two compilation errors with J2ObjC:
- TypeAnnotation.java:8: error: TYPE_USE cannot be resolved or is not a field
- TypeAnnotation.java:13: error: The annotation @TypeAnnotation is disallowed for this location

```java
package javax.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Target;
import java.util.LinkedList;
import java.util.List;

@Target(ElementType.TYPE_USE)
public @interface TypeAnnotation {
    
    public static class Test {
        
        public static final List<@TypeAnnotation String> EXAMPLE = new LinkedList<>();
        
    }
    
}
```

And as a file: [TypeAnnotation.java](https://github.com/google/j2objc/files/178564/TypeAnnotation.java.txt)

And to be clear: I don't need a specific behavior other than that this file compiles (so there is nothing to "test"). Just stripping all type annotations from the source code is totally acceptable to me! :-)

(In case it matters, I'm using the custom script `"${J2OBJC_HOME}/j2objc" -d ${PROJECT_DIR}/Objc -sourcepath ${PROJECT_DIR}/Java --no-package-directories -use-arc --prefixes prefixes.properties --doc-comments --swift-friendly -source 8 --generate-deprecated -g ${INPUT_FILE_PATH};` as a build rule directly in Xcode.)

**Comment by tomball** [comment]
The problem is that TYPE_USE was added to ElementType in Java 8, but j2objc's JRE still has the Java 7 version. As a temporary workaround, you can just add TYPE_USE to jre_emul/android/libcore/luni/src/main/java/java/lang/annotation/ElementType.java and rebuild. We'll do an official upgrade to Java 8's java.lang.annotation next week.

**Comment by KasparEtter** [comment]
Thanks for your suggestion and I'm looking forward to the official upgrade of J2ObjC!

**Comment by tomball** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/5cf46a111f89e3dd32fe08cbabb55b5a8270988b).

**Comment by KasparEtter** [comment]
Thanks for the fix! The errors disappeared. However, I'm running into a new issue and I'm not sure whether its due to my incompetence or whether you introduced a new bug: `'java/lang/String.h' file not found` (in the cross-compiled .m files of Java sources that reference the String class). I guess you have enough test cases in place to catch such problems, so I'm looking more into this myself (or alternatively, I could open a new issue if you prefer).

**Comment by kstanger** [comment]
It would be very surprising if something like that would make it through
all of our tests. If you can provide an example .java source file that
emits a java/lang/String.h include, please file another bug!
