### ISSUE TITLE
Missing headers in include/android/

### ISSUE THREAD

**Issue by raymondChan23** [google/j2objc#2081]
run project and get some errors related to android/text

Showing All Errors Only
Undefined symbol: _AndroidTextTextUtils_isEmptyWithJavaLangCharSequence_
Undefined symbol: _AndroidTextTextUtils_joinWithJavaLangCharSequence_withJavaLangIterable_
Undefined symbol: _AndroidUtilLog_dWithNSString_withNSString_

It seems that some folders and headers are missing from the latest code 
by using the "make -j8 dist" command, as compared to the j2objc-2.8.zip release. 
The missing folders and headers are:

/include/android/os
/include/android/test
/include/android/text
/include/android/util

I'm wondering if you could help me resolve this issue.
Thank you for your help.

**Comment by tomball** [comment]
As a workaround, try copying the missing headers from 2.8 into a separate directory, then copying the lib/libandroid_util.a file to that directory, and include that directory in your project's include and lib paths. These files haven't changed since 2.8.

**Comment by raymondChan23** [comment]
> As a workaround, try copying the missing headers from 2.8 into a separate directory, then copying the lib/libandroid_util.a file to that directory, and include that directory in your project's include and lib paths. These files haven't changed since 2.8.

Thanks. 
it works in iphone after copying the 2.8.zip libandroid_util.a & 
related directories into the project, add lib & header search paths, 
But it cannot run in simulator because of [arm64](ld: symbol(s) not found for architecture arm64).
could it be resolved?
