### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by kangert** [google/j2objc#1094]
I get the following error when I try to compile iOS project to work with Mac Catalyst (for **macOS Catalina**):

`.../lib/libjre_emul.a(ErrnoException.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/admin/Documents/Workspaces/j2objc/lib/libjre_emul.a' for architecture x86_64`

**Comment by tomball** [comment]
We got those errors several iOS versions back, when Xcode started differentiating between iOS x86 (simulator) and macOS x86. Since these object files have the same architecture, they cannot be added to the same static library. Since j2objc's focus is on iOS, we therefore split off the macOS libraries into $J2OBJC_HOME/lib/macosx/ (iOS apps still use $J2OBJC_HOME/lib).

I assume since Mac Catalyst builds macOS X apps, your project should specify the macosx subdirectory. On your system, that would be '/Users/admin/Documents/Workspaces/j2objc/lib/macosx'.

**Comment by tomball** [comment]
Please reply whether this works for your app. I can't verify it because Google hasn't deployed Catalina internally.

**Comment by tomball** [comment]
From @kanger:
Thank you for your quick reply on:
#1094 (comment)

However Catalyst would probably need a special version of the library:
../lib/macosx/libjre_emul.a(ErrnoException.o), building for Mac Catalyst, but linking in object file built for macOS, file '/Users/admin/Documents/Workspaces/j2objc/lib/macosx/libjre_emul.a' for architecture x86_64

**Comment by tomball** [comment]
Unfortunately, we can't fix it until Catalina is released in-house.

If you want to try hacking our build in the meantime, do a case-insensitive search for "macosx" in the jre_emul, make, and scripts directories. Since the macosx directory and its static libraries are built separately from the iOS support, it should be straightforward to apply the same deltas for a catalyst directory. [The CFLAG appears to be "-target x86_64-apple-ios13.0-macabi".](https://stackoverflow.com/questions/56487645/how-to-compile-a-3rd-party-library-to-be-used-with-uikit-for-mac-catalyst)

**Comment by 666tos** [comment]
@tomball I recently had to create POC for simple `Catalyst` app using `FFMpeg`.
I created build scripts to build `XCFramework` for `iOS, tvOS, Mac and MacCatalyst` platforms.
Since `J2ObjC` is also using `make` build system, it may be worth checking it: https://github.com/666tos/FFMpeg/tree/xcframework

**Comment by tomball** [comment]
Cool, thanks for your help!

**Comment by kangert** [comment]
Thank you for the info and for the "hack tip", but I will wait for your professional version :). I tried to modify the build scripts, but the scripts are quite complex and I'm really not an expert on it. When I simply switch `macosx ` to `-target x86_64-apple-ios-macabi` many compilation errors come out like:

```
/Users/admin/Test/j2objc/jre_emul/build_result/Classes/java/lang/System.m:28:9: fatal error: 
      'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
```
on

```
#if TARGET_OS_IPHONE || TARGET_OS_SIMULATOR
#import <UIKit/UIKit.h>
#endif
```

So I only hope that Google in-house distributions of new systems are faster than in my company since It usually takes a couple of years :).

**Comment by tomball** [comment]
UIKit.h was added to the macOS SDK in Xcode 11, so that has to be installed first. You can install multiple versions of Xcode on your system as long as you rename the app before dragging it into your /Applications folder. `sudo xcode-select --path` then switches what version is used by the command-line.

Google jumps on new macOS releases quickly, so my hope is by the end of the month (depends on what bugs are found in pilot testing).

**Comment by kangert** [comment]
Any update on this?

**Comment by 666tos** [comment]
Any update on this?

**Comment by tomball** [comment]
Still waiting on the corporate rollout of Catalina -- it started a couple of weeks ago, then had to be pulled back due to deployment bugs. This remains on the top of my todo list after I am able to upgrade.

**Comment by 666tos** [comment]
Hey @tomball, did not hear from you for almost 2 month, so it's my turn to ask: any update on this?

**Comment by tomball** [comment]
Sorry, it's been busy as the other engineer moved to a new project. However, I should be able to work on it today. 

I found this article on [building a static library with normal and catalyst archs](https://onesignal.com/blog/mac-catalyst-fat-framework/). It looks like the main takeaway is to add the **x86_64h** arch, which should be straightforward since we already support so many iOS archs. Do you see any other issues?

**Comment by tomball** [comment]
Fixed in current source ([build instructions here](https://developers.google.com/j2objc/guides/building-j2objc)).

**Comment by tomball** [comment]
Please note that all I've verified is that the architecture slice built successfully and was added to all libraries. Mac Catalyst requires that a registered AppStore ID be used during the build, and won't allow test apps like our team uses to be built (as far as I can figure out). Assuming you have a registered iOS app ID, please build your app for Mac Catalyst and let us know at j2objc-discuss@ whether you were successful.

**Comment by tomball** [comment]
I figured out how to link test apps with Mac Catalyst, and found that Xcode won't link an x86_64h architecture. We therefore need to create a separate set maccatalyst libraries with just that slice, like we had to do for macosx.

**Comment by tomball** [comment]
Added separate libraries, in lib/maccatalyst/*

**Comment by 666tos** [comment]
@tomball are you planning to release pre-built libraries for mac catalyst?
I'm trying to build it with protobuf support, but that's a bit tricky and requires adjustments on every small step

**Comment by tomball** [comment]
We want to build the frameworks to use XCFramework instead of fat
libraries, since Mac Catalyst showed that a single fat library can no
longer hold all supported architectures. However, releasing a new
distribution is not a high priority for us right now, as there’s a lot
going on these days. 😷

However, anyone can make their own distribution bundle. Check that your
system has the requirements in the Building J2ObjC
<https://developers.google.com/j2objc/guides/building-j2objc> page. Protocol
Buffers need to be installed
<https://developers.google.com/j2objc/guides/building-j2objc#optional_setup_for_protocol_buffers>
(version 3.11.1, not 3.3.0), but you can install that using Homebrew
<https://brew.sh/> (brew install protobuf) if you don't want to build it
from source (any Homebrew version after 3.11 is fine). Then run:

$ git clone https://github.com/google/j2objc.git
$ cd j2objc
$ ./scripts/build_distribution.sh <version> <protobuf-install-dir>

The version number can be any string you want, and the protobuf-install-dir
is wherever you built it; the default Homebrew uses is /usr/local. Then
unzip the distribution zip file (j2objc-<version>.zip) like you would a
normal distribution.

**Comment by kangert** [comment]
The linker is still not happy:

> ld: object file /Users/admin/Documents/Workspaces/j2objc/lib/maccatalyst/libjre_emul.a(ErrnoException.o) was built for different x86_64 sub-type (8) than link command line (3) file '/Users/admin/Documents/Workspaces/j2objc/lib/maccatalyst/libjre_emul.a'

**Comment by tomball** [comment]
So what's the right sub-type? I'm stuck with StackOverflow answers, since I can't find any documentation from Apple.

The flags are set at this line: [make/fat_lib_macros.mk:55](https://github.com/google/j2objc/blob/master/make/fat_lib_macros.mk#L55).  Perhaps the right flags can be found in an expanded log line from your failing Mac Catalyst project, as the JRE classes should be compiled with a related set of flags as your app. To rebuild, run "make -j8 clean && make -j8 dist".

**Comment by tomball** [comment]
When you have a working make/fat_lib_macros.mk, please [submit a pull request](https://developers.google.com/j2objc/guides/how-to-contribute).

**Comment by kangert** [comment]
Thanks. And you are right, there is almost no info anywhere. Nobody even seems to have any problem with Catalyst (either that or nobody uses it).
 
I will try some architecture/target combinations (in the expanded log is a newer target ...ios13.2-macabi).

The log from a newly created test app AAA (Xcode 11.3.1):
```
Build target AAA of project AAA with configuration Debug

Ld /Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Products/Debug-maccatalyst/AAA.app/Contents/MacOS/AAA normal x86_64 (in target 'AAA' from project 'AAA')
    cd /Users/admin/Desktop/AAA
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.2-macabi -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Products/Debug-maccatalyst -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/usr/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/maccatalyst -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/usr/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/maccatalyst -F/Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Products/Debug-maccatalyst -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/System/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/System/Library/Frameworks -filelist /Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Intermediates.noindex/AAA.build/Debug-maccatalyst/AAA.build/Objects-normal/x86_64/AAA.LinkFileList -Xlinker -rpath -Xlinker @loader_path/../Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -object_path_lto -Xlinker /Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Intermediates.noindex/AAA.build/Debug-maccatalyst/AAA.build/Objects-normal/x86_64/AAA_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -force_load /Users/admin/Documents/Workspaces/j2objc/lib/maccatalyst/libjre_emul.a -liconv -Xlinker -dependency_info -Xlinker /Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Intermediates.noindex/AAA.build/Debug-maccatalyst/AAA.build/Objects-normal/x86_64/AAA_dependency_info.dat -o /Users/admin/Library/Developer/Xcode/DerivedData/AAA-bmctjimbybysvocnksuolbmwdoec/Build/Products/Debug-maccatalyst/AAA.app/Contents/MacOS/AAA

ld: object file /Users/admin/Documents/Workspaces/j2objc/lib/maccatalyst/libjre_emul.a(ErrnoException.o) was built for different x86_64 sub-type (8) than link command line (3) file '/Users/admin/Documents/Workspaces/j2objc/lib/maccatalyst/libjre_emul.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kangert** [comment]
I changed two lines (55 and 56) in **fat_lib_macros.mk**:

`
FAT_LIB_MAC_CATALYST_FLAGS = $(FAT_LIB_OSX_FLAGS) -arch x86_64h -DJ2OBJC_BUILD_ARCH=x86_64h \`
**to**
`FAT_LIB_MAC_CATALYST_FLAGS = $(FAT_LIB_OSX_FLAGS) -arch x86_64 -DJ2OBJC_BUILD_ARCH=x86_64 \`

and

`--target=x86_64-apple-ios13-macabi \`
    **to**
`--target=x86_64-apple-ios13.2-macabi \`

And it works. The second line is probably not necessary. So only arch **x86_64h** to **x86_64**.

**Comment by tomball** [comment]
Awesome! I'm building it now, and will update at least one of the iOS examples to verify it builds (always good to have verification from multiple systems).

**Comment by tomball** [comment]
I made the x86_64h => x86_64 change (you were right that the --target change didn't matter), verified it with the examples/Hello app, and committed it. I can't commit the examples/Hello update because for it to support both iOS and Mac Catalyst, j2objc's frameworks need to be changed to XCFramework.

**Comment by top-master** [comment]
I had similar error log:
```
... building for Mac Catalyst, but linking in object file built for macOS ...
```

### Fix:
The fix was to ensure the right flag really gets passed to `clang`-compiler !!
I mean, although "`-target x86_64-apple-ios13.6-macabi`" was in flags it was never reaching the compiler (due to a mistake).

### Testing:
If below causes compile-error (no matter if C, C++, Obj-C), then you have the same issue.
```
#ifdef __APPLE__
#   include <TargetConditionals.h>
#   if !TARGET_OS_MACCATALYST
#       error "Unsupported platform!"
#   endif
#endif
```

### Background
I was implementing [CMake iOS toolchain](https://github.com/top-master/cmake-ios-toolchain),
which supports `iOS`, Mac's `Catalyst` and maybe `tvOS` and `watchOS`
(because even in 2021, `CMake` still does not have built-in support).

**Comment by tomball** [comment]
What was the actual fix? Do you have a diff?

**Comment by top-master** [comment]
You guys already fixed it!
I mean, Google-search brought me here and just wanted to mention the actual cause
(and that it's not `x86_64` vs `x86_64h` related).

**Comment by tomball** [comment]
Thanks for the feedback!
