### ISSUE TITLE
Enums are broken since 1.0?

### ISSUE THREAD

**Issue by davidganster** [google/j2objc#783]
In 0.9.8.2.1, the following enum compiled just fine:

```java
public class LogLevel {

    public static final LogLevel DEBUG   = new LogLevel(0);
    public static final LogLevel VERBOSE = new LogLevel(1);
    public static final LogLevel INFO    = new LogLevel(2);
    public static final LogLevel WARN    = new LogLevel(3);
    public static final LogLevel ERROR   = new LogLevel(4);

    private int level;
    private LogLevel(int level) { this.level = level; }
    public boolean smallerThanOrEqualTo(LogLevel o) {
        return this.level <= o.level;
    }

}
```

It would translate to:

```objective-c
#ifndef ComPackageName.h
#define ComPackageName.h

#include "J2ObjC_header.h"

@interface SCLLogLevel : NSObject

#pragma mark Public

- (jboolean)smallerThanOrEqualToWithSCLLogLevel:(SCLLogLevel *)o;

@end

J2OBJC_STATIC_INIT(SCLLogLevel)

FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_DEBUG__;
J2OBJC_STATIC_FIELD_GETTER(SCLLogLevel, DEBUG__, SCLLogLevel *)

FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_VERBOSE_;
J2OBJC_STATIC_FIELD_GETTER(SCLLogLevel, VERBOSE_, SCLLogLevel *)

FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_INFO_;
J2OBJC_STATIC_FIELD_GETTER(SCLLogLevel, INFO_, SCLLogLevel *)

FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_WARN_;
J2OBJC_STATIC_FIELD_GETTER(SCLLogLevel, WARN_, SCLLogLevel *)

FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_ERROR_;
J2OBJC_STATIC_FIELD_GETTER(SCLLogLevel, ERROR_, SCLLogLevel *)

J2OBJC_TYPE_LITERAL_HEADER(SCLLogLevel)

@compatibility_alias ComPackagenameLoggingLevel SCLLogLevel;

#endif // ComPackageName.h
```

But, since 1.0 it translates to

```objective-c
#include "J2ObjC_header.h"

#pragma push_macro("ComPackageNameLoggingLogLevel_INCLUDE_ALL")
#ifdef ComPackageNameLoggingLogLevel_RESTRICT
#define ComPackageNameLoggingLogLevel_INCLUDE_ALL 0
#else
#define ComPackageNameLoggingLogLevel_INCLUDE_ALL 1
#endif
#undef ComPackageNameLoggingLogLevel_RESTRICT

#if !defined (SCLLogLevel_) && (ComPackageNameLoggingLogLevel_INCLUDE_ALL || defined(SCLLogLevel_INCLUDE))
#define SCLLogLevel_

@interface SCLLogLevel : NSObject

#pragma mark Public

- (jboolean)smallerThanOrEqualToWithSCLLogLevel:(SCLLogLevel *)o;

@end

J2OBJC_STATIC_INIT(SCLLogLevel)

inline SCLLogLevel *SCLLogLevel_get_DEBUG();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_DEBUG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)

inline SCLLogLevel *SCLLogLevel_get_VERBOSE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_VERBOSE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, VERBOSE, SCLLogLevel *)

inline SCLLogLevel *SCLLogLevel_get_INFO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_INFO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, INFO, SCLLogLevel *)

inline SCLLogLevel *SCLLogLevel_get_WARN();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_WARN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, WARN, SCLLogLevel *)

inline SCLLogLevel *SCLLogLevel_get_ERROR();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT SCLLogLevel *SCLLogLevel_ERROR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, ERROR, SCLLogLevel *)

J2OBJC_TYPE_LITERAL_HEADER(SCLLogLevel)

@compatibility_alias ComPackageNameLoggingLogLevel SCLLogLevel;

#endif

#pragma pop_macro("ComPackageNameLoggingLogLevel_INCLUDE_ALL")
```

Which doesn't compile in Xcode 7.3.1.
The error message says:

`Interface type 'SCLLogLevel' cannot be passed by value; did you forget * in 'SCLLogLevel'?`
`Conflicting types for 'J2OBJC_STATIC_FIELD_OBJ_FINAL'`
`Expected ';' after top level declarator`

and a warning in the same line:
`Type specifier missing, defaults to 'int'`.

I'm using the j2objc-gradle plugin to do the translation, but I don't think that's the problem, since the translated files themselves seem to be erroneous.

Any ideas as to what is going wrong here?

**Comment by kstanger** [comment]
Your java code translates and compiles fine for me. Can you include the expanded compiler command and output so I can see which lines of code it's complaining about?

**Comment by davidganster** [comment]
Sorry, maybe I should have added that I'm working with swift.
The final compiler message is `Failed to import bridging header ...`.

I tried to shorten the output to the relevant lines:

```
/Users/.../File.h:10:
#import "JavaSources.h"
        ^
/Users/.../JavaSources.h:76:
#import "at/wirecube/core/logging/LogLevel.h"
        ^
error: interface type 'SCLLogLevel' cannot be passed by value; did you forget * in 'SCLLogLevel'?
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
                                         ^
error: expected parameter declarator
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
                                           ^
<command line>:12:15: note: expanded from here
#define DEBUG 1
              ^

error: expected ')'
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
                                           ^
<command line>:12:15: note: expanded from here
#define DEBUG 1
              ^

note: to match this '('
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
                             ^
warning: type specifier missing, defaults to 'int'
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
^

error: conflicting types for 'J2OBJC_STATIC_FIELD_OBJ_FINAL'
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
^
/Users/.../SomeFile.h:52:1: note: previous declaration is here
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCRouterConfigManager, BEACON_TYPE_IDENTIFIER_ESTIMOTE, NSString *)
^

error: expected ';' after top level declarator
J2OBJC_STATIC_FIELD_OBJ_FINAL(SCLLogLevel, DEBUG, SCLLogLevel *)
                                                                ^
```

Here is a screenshot:

![screen shot 2016-08-24 at 17 21 31](https://cloud.githubusercontent.com/assets/851282/17936503/4b5dee7e-6a1f-11e6-9228-e9f3c0b23653.png)


The failing compiler command looks like this (shortened as well)

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file ${SWIFT_FILES} -target arm64-apple-ios9.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -I /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Products/Debug-iphoneos -F /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Products/Debug-iphoneos -F /PathToProject/ProjectName -enable-testing -g -import-objc-header /ProjectSpecificPath/ProjectName-Bridging-Header.h -module-cache-path /Users/myusername/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/swift-overrides.hmap -Xcc -iquote -Xcc /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/ProjectName-generated-files.hmap -Xcc -I/PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/ProjectName-own-target-headers.hmap -Xcc -I/PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/ProjectName-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/all-product-headers.yaml -Xcc -iquote -Xcc /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/ProjectName-project-headers.hmap -Xcc -I/PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Products/Debug-iphoneos/include -Xcc -I/PathToPods/Pods/geos/include -Xcc -I/PathToPods/Pods/geos/capi -Xcc -I/PathToJ2Objc/ -Xcc -I/PathToPods/Pods/Headers/Public -Xcc -I/PathToPods/Pods/Headers/Public/j2objc-transpiled-project-core-debug -Xcc -I/PathToPods/Pods/Headers/Public/j2objc-transpiled-project-core-release -Xcc -I/PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/DerivedSources/arm64 -Xcc -I/PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -working-directory/PathToProject/ProjectName -emit-module-doc-path /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/Objects-normal/arm64/SomeProtocol~partial.swiftdoc -Onone -module-name ProjectName -emit-module-path /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/Objects-normal/arm64/SomeProtocol~partial.swiftmodule -serialize-diagnostics-path /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/Objects-normal/arm64/SomeProtocol.dia -emit-dependencies-path /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/Objects-normal/arm64/SomeProtocol.d -emit-reference-dependencies-path /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/Objects-normal/arm64/SomeProtocol.swiftdeps -o /PathToProject-fxkyhojmycjlsmbqrvgwpnnwvytt/Build/Intermediates/ProjectName.build/Debug-iphoneos/ProjectName.build/Objects-normal/arm64/SomeProtocol.o -embed-bitcode-marker
```

I get errors like these in every swift file that uses generated obj-c code, and for every enum.
Thanks for the help!

**Comment by kstanger** [comment]
I can't tell if swift is having trouble with the J2OBJC_STATIC_FIELD_OBJ_FINAL macro or the "DEBUG" name of your constant. Do you get the same errors for all the other constants?

**Comment by davidganster** [comment]
Yes, I get the same errors for all the constants. :(

**Comment by kstanger** [comment]
Did you update your j2objc runtime to the new version and update your header search paths to point at it? The "previous declaration is here" message for J2OBJC_STATIC_FIELD_OBJ_FINAL makes me suspicious that the compiler never saw the macro as defined in J2ObjC_header.h.

**Comment by davidganster** [comment]
Thank you, that was spot on. It seems upgrading the j2objc version and then doing a `pod install` with the new podspec didn't remove the old header and library search paths from the workspace. Deleting the workspace file and doing a clean `pod install` did the trick.

**Comment by davidganster** [comment]
Sorry for reopening the issue, but I think this is better than opening a new one.

I got the generated files to compile, but I cannot access enum types that are declared within a class like this:

```java
public class MyClass {
  public enum EnumName {
    Type1, Type2
  }
}
```


I get `Use of unresolved identifier 'EnumName'` when trying to access the enum in swift. In objc, I also cannot use the enum type, because `Receiver 'EnumName' for class message is a forward declaration`.

I used the `--swift-friendly` flag to transpile the java sources. 
Looking at the generated file, I see the following preprocessor macro right before the enum type is defined (there is a forward declaration at the top of the file, which is why objc can see it):

`#if !defined (EnumName_) && (INCLUDE_ALL_PackageNameMyClass || defined(INCLUDE_MyClass_EnumName))`

It seems like this condition is never true? 
I'm now using release 1.1.

**Comment by kstanger** [comment]
The names of inner types will be appended to the name of the outer type with an underscore delimiter. So in your case your enum type will be called "MyClass_EnumName".

The preprocessor macros that you're seeing are part of [Segmented Headers](http://j2objc.org/docs/Segmented-Headers.html), which as far as I know are not a problem for Swift bridging, but I could be wrong. They can be disabled with `--no-segmented-headers`

**Comment by davidganster** [comment]
I failed to realize I had to include the generated headers using the `#include` directive instead of `#import`.
Thank you once more, I owe you a 🍺
